### ISSUE TITLE
How do you specify the source and destination files in the config?

### ISSUE THREAD

**Issue by hoaboat** [cssjanus/grunt-cssjanus#10]
I can't find documentation on how to point to a source and destination file.

**Comment by Krinkle** [comment]
Hi @hoaboat,

This plugin uses the Grunt multi-task concept. As such there's a wide variety of options for matching files and associating source files to destination paths. See http://gruntjs.com/configuring-tasks for more information. The configuration is processed by Grunt, and handed off to grunt-cssjanus for each individual file. This plugin is not aware of how source and destination file are specified in the Grunt configuration.

I've added a basic usage section to the readme in 58d858dce93f7b2. I hope that helps!
