### ISSUE TITLE
Issue with glob as path

### ISSUE THREAD

**Issue by xjamundx** [cssjanus/grunt-cssjanus#11]
I tried to follow one of your examples (and the similar grunt examples) and it won't work. This was for the **Transform in-place** option.

Tried both of these varations, with the same result:

```js
build: { src: ['.build/css/*.rtl.css'] }
```

```
build: { src: ['.build/css/app.rtl.css'] }
```

The result is this:
`Warning: Unable to write "undefined" file (Error code: undefined). Use --force to continue.`

I looked at the code and I'm pretty sure I know why it's happening. Add this `console.log(f.src, f.dest);` here:
https://github.com/cssjanus/grunt-cssjanus/blob/58d858dce/tasks/cssjanus.js#L21

And you'll see that `f.dest` is undefined. You'll also see that `f.src` is an `Array` and not a single path.

Let me know if I can help!

**Comment by xjamundx** [comment]
Short-term workaround is this:

```js
		build: {
			files: grunt.file.expand('.build/css/*.rtl.css').reduce(function(prev, curr) { prev[curr] = curr; return prev; }, {})
		}
```

**Comment by Krinkle** [comment]
I don't think Grunt intended to support the "Transform in-place" pattern. I can't find it at <http://gruntjs.com/configuring-tasks>. Grunt plugins like [grunt-contrib-uglify](https://github.com/gruntjs/grunt-contrib-uglify) don't support it either. I propose we remove it from the readme file.
