### ISSUE TITLE
Can someone npm publish v0.3.0?

### ISSUE THREAD

**Issue by jdforrester** [cssjanus/grunt-cssjanus#13]
It was tagged in February but is not released yet. It's blocking users from upgrading to grunt 1.0.0.

**Comment by yoavf** [comment]
Just published (0.3.2, I messed up the process a couple of times - sorry)

**Comment by jdforrester** [comment]
Thank you.

In future, if the npm-publish step goes wrong, please publish it as 0.3.0-fix or something. You've now broken the link between npm versions and code versions.
