### ISSUE TITLE
Moving to cssjanus org?

### ISSUE THREAD

**Issue by Krinkle** [cssjanus/grunt-cssjanus#5]
Hi @yoavf!

Would you be interested in transferring this repository to the cssjanus GitHub organisation? You'd retain administrative access as co-owner.

Thanks!

**Comment by yoavf** [comment]
Sure, would love to. Let me know when I have admin rights there to be able to initiate the transfer.

**Comment by Krinkle** [comment]
@yoavf Hmmm. GitHub allows one to move a repo to another use (who then has to accept the transfer), but this acceptance feature doesn't exist for organisations. Can you transfer it to me? I'll move it from there to @cssjanus.

GitHub will keep redirects in place to the final destinations so that any forks, local clones, as well the issue tracker and http(s) urls, etc. keep working.

**Comment by yoavf** [comment]
Done :).
